export const welcomePrompts = [
    "Think bigger.",
    "The future scales from here.",
    "Tomorrow starts with a number.",
    "Your next breakthrough awaits.",
    "The age of abundance is here.",
    "Create without limits.",
    "Progress begins with scale.",
    "A bigger future is possible.",
    "Scale your ambitions.",
    "Imagine more.",
    "Greatness starts small.",
    "Your potential, multiplied.",
    "Small inputs. Massive outcomes.",
    "Unlock the power of scale.",
    "Today's numbers. Tomorrow's world.",
    "Push beyond what's possible.",
    "Lead with magnitude.",
    "The best time to scale was yesterday. The second best time is now.",
    "What could your number become?",
    "Your future self thinks in megas.",
    "Every transformation starts with a single input.",
    "The world rewards those who think bigger.",
    "Success is just scale, applied consistently.",
    "You weren't born to use base units.",
    "A thousand opportunities begin here.",
    "Think exponential.",
    "Growth starts with a mindset.",
    "Be the force multiplier.",
];
