export const welcomePrompts = [
    "Think bigger.",
    "The future scales from here.",
    "The age of abundance is here.",
    "Create without limits.",
    "Progress begins with scale.",
    "A bigger future is possible.",
    "Scale your ambitions.",
    "Imagine more.",
    "Greatness starts small.",
    "Your potential, multiplied.",
    "Small inputs. Massive outcomes.",
    "Lead with magnitude.",
    "What could your value become?",
    "The world rewards those who think bigger.",
    "You weren't born to use base units.",
    "A thousand opportunities begin here.",
    "Think exponential.",
    "Growth starts with a mindset.",
    "Be the force multiplier.",
    "Your quantity has untapped potential.",
    "Most values think too small.",
    "The next million starts here.",
    "Unlock latent magnitude.",
    "Expand your addressable scale.",
    "Some numbers are ready to grow.",
    "Magnitude is a mindset.",
    "Give your value room to scale.",
    "Your metric deserves a bigger future.",
    "Don't let your units limit you.",
    "The future belongs to larger numbers.",
    "Convert ambition into magnitude.",
    "Realize your quantity's potential.",
    "The world's most ambitious ideas start small.",
    "Modern magnitude for a changing world.",
    "Creating opportunity through scale.",
    "Enabling magnitude at global scale.",
    "Improve your unit economics.",
];
