export const welcomePrompts = [
    "Think bigger.",
    "The future scales from here.",
    "The age of abundance is here.",
    "Create without limits.",
    "Progress begins with scale.",
    "A bigger future is possible.",
    "Scale your ambitions.",
    "Imagine more.",
    "Greatness starts small.",
    "Your potential, multiplied.",
    "Small inputs. Massive outcomes.",
    "Lead with magnitude.",
    "What could your value become?",
    "The world rewards those who think bigger.",
    "You weren't born to use base units.",
    "A thousand opportunities begin here.",
    "Think exponential.",
    "Growth starts with a mindset.",
    "Be the force multiplier.",
];
