export const units = [
    { name: "meter", symbol: "m", mega: "Mm" },
    { name: "kilogram", symbol: "kg", mega: "Mkg" },
    { name: "second", symbol: "s", mega: "Ms" },
    { name: "ampere", symbol: "A", mega: "MA" },
    { name: "kelvin", symbol: "K", mega: "MK" },
    { name: "mole", symbol: "mol", mega: "Mmol" },
    { name: "candela", symbol: "cd", mega: "Mcd" },
    { name: "radian", symbol: "rad", mega: "Mrad" },
    { name: "steradian", symbol: "sr", mega: "Msr" },
    { name: "hertz", symbol: "Hz", mega: "MHz" },
    { name: "newton", symbol: "N", mega: "MN" },
    { name: "pascal", symbol: "Pa", mega: "MPa" },
    { name: "joule", symbol: "J", mega: "MJ" },
    { name: "watt", symbol: "W", mega: "MW" },
    { name: "coulomb", symbol: "C", mega: "MC" },
    { name: "volt", symbol: "V", mega: "MV" },
    { name: "farad", symbol: "F", mega: "MF" },
    { name: "ohm", symbol: "\u03a9", mega: "M\u03a9" },
    { name: "siemens", symbol: "S", mega: "MS" },
    { name: "weber", symbol: "Wb", mega: "MWb" },
    { name: "tesla", symbol: "T", mega: "MT" },
    { name: "henry", symbol: "H", mega: "MH" },
    { name: "Celsius", symbol: "\u00b0C", mega: "M\u00b0C" },
    { name: "lumen", symbol: "lm", mega: "Mlm" },
    { name: "lux", symbol: "lx", mega: "Mlx" },
    { name: "becquerel", symbol: "Bq", mega: "MBq" },
    { name: "gray", symbol: "Gy", mega: "MGy" },
    { name: "sievert", symbol: "Sv", mega: "MSv" },
    { name: "katal", symbol: "kat", mega: "Mkat" },
    { name: "inch", symbol: "in", mega: "Min" },
    { name: "foot", symbol: "ft", mega: "Mft" },
    { name: "yard", symbol: "yd", mega: "Myd" },
    { name: "mile", symbol: "mi", mega: "Mmi" },
    { name: "pound", symbol: "lb", mega: "Mlb" },
    { name: "ounce", symbol: "oz", mega: "Moz" },
    { name: "gallon", symbol: "gal", mega: "Mgal" },
    { name: "furlong", symbol: "fur", mega: "Mfur" },
    { name: "chain", symbol: "ch", mega: "Mch" },
    { name: "rod", symbol: "rd", mega: "Mrd" },
    { name: "cubit", symbol: "cubit", mega: "Mcubit" },
    { name: "span", symbol: "span", mega: "Mspan" },
    { name: "barleycorn", symbol: "bc", mega: "Mbc" },
    { name: "smoot", symbol: "smoot", mega: "Msmoot" },
    { name: "beard-second", symbol: "bs", mega: "Mbs" },
    { name: "warhol", symbol: "wh", mega: "Mwh" },
    { name: "alignment sprint", symbol: "as", mega: "Mas" },
    { name: "productivity aura", symbol: "pa", mega: "Mpa" },
    { name: "OKR vapor", symbol: "okr", mega: "Mokr" },
    { name: "founder radius", symbol: "fr", mega: "Mfr" },
    { name: "stakeholder glow", symbol: "sg", mega: "Msg" },
    { name: "agentic unit", symbol: "au", mega: "Mau" },
    { name: "cloud resonance", symbol: "cr", mega: "Mcr" },
    { name: "dashboard gravitas", symbol: "dg", mega: "Mdg" },
    { name: "epistemic liquidity", symbol: "el", mega: "Mel" }
];
